[package]
name = "ricochetrustsolver"
version = "0.1.0"
authors = ["Andreas From <andro.from@gmail.com>"]

[dependencies]
fnv = "1.0.2"
generic-array = "0.2.0"
typenum = "1.3.0"
num = "0.1"

[profile.release]
debug = true
